### ISSUE TITLE
Broadcast predicate methods should work even when private

### ISSUE THREAD

**Issue by jordanbyron** [betterup/wisper-activejob-broadcaster#6]
While working with the new predicate based early escape functionality added in #3, I was surprised that the predicate methods I defined didn't work because I marked them as private.

```ruby
class MyAwesomeListener < ApplicationJob
  include Wisper::ActiveJob::Subscriber

  def awesome_thing_created(thing)
    thing.celebrate!
  end

  private

  # I'm not checked because I am private 😢 
  #
  def perform_awesome_thing_created?(thing)
    thing.awesome?
  end 
end
```

Relevant code:

https://github.com/betterup/wisper-activejob-broadcaster/blob/94b23eb5f0e375fb910dfa80b4c0a2c56a3c55be/lib/wisper/activejob/broadcaster.rb#L16

`respond_to?` takes an optional second argument which will include `private` and `protected` methods. Any objections to making this change? IMO marking these predicate methods as private helps differentiate the non-predicate methods as well as keeping them out of the listener's public API.

cc/ @Esaron

**Comment by Esaron** [comment]
No objections from me!
